### ISSUE TITLE
k256 does not compile without allocator

### ISSUE THREAD

**Issue by StackOverflowExcept1on** [RustCrypto/elliptic-curves#1057]
```
error: no global memory allocator found but one is required; link to std or add `#[global_allocator]` to a static item that implements the GlobalAlloc trait

error: could not compile `app` (bin "app") due to 1 previous error
```

```toml
[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies]
k256 = { version = "0.14.0-pre.0", default-features = false, features = ["arithmetic"] }
libc = { version = "0.2.155", default-features = false }
rand_core = { version = "0.6.4", default-features = false, features = ["getrandom"] }

[profile.dev]
panic = "abort"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
```

```rust
#![no_std]
#![no_main]

extern crate libc;

use k256::SecretKey;
use rand_core::OsRng;

#[no_mangle]
extern "C" fn main() -> i32 {
    if f().to_bytes()[0] == 0xff {
        1
    } else {
        0
    }
}

#[no_mangle]
#[inline(never)]
pub fn f() -> SecretKey {
    SecretKey::random(&mut OsRng)
}

#[panic_handler]
fn panic_handler(_: &core::panic::PanicInfo) -> ! {
    loop {}
}
```
