### ISSUE TITLE
secp256k1 Schnorr (BIP340) signatures not verifying

### ISSUE THREAD

**Issue by mikedilger** [RustCrypto/elliptic-curves#686]
I'm trying to write a nostr client which uses BIP340 signing.  I've got some bonafide event data from a relay that I presume is correct.  However, the signature does not verify when I use k256::schnorr to check it.  BTW, it does verify with secp256k1 library (but that library interface is ugly so I wanted to use k256 even though it is slower).

The data is in the code below:
````rust
use k256::schnorr::{VerifyingKey, Signature};
use k256::schnorr::signature::Verifier;
use std::error::Error;
use std::convert::TryFrom;

fn publickey_hex() -> &'static str {
    "ee11a5dff40c19a555f41fe42b48f00e618c91225622ae37b6c2bb67b76c4e49"
}

fn verify(id: &str, sig: &str) -> Result<(), Box<dyn Error>>
{
    let id_bytes = hex::decode(&id)?;
    let signature = Signature::try_from(&*hex::decode(&sig)?)?;
    let verifying_key = VerifyingKey::from_bytes(&hex::decode(&publickey_hex())?)?;
    verifying_key.verify(&id_bytes, &signature)?;
    println!("Verified OK");
    Ok(())
}

fn main() -> Result<(), Box<dyn Error>>
{
    // These came from a bonafide nostr relay. They ought to verify.
    let id = "654c934fb675c3cd33c292ddf868e149f55dfe813c0ea2ff5b9f3738abd06bc2";
    let sig = "928894627057b93072069f8d4743844923d945055bb2bf24fb9200566b35b5b30a338af5bdc129c82f1db00fd96dabba51c645520456213c915fc9dda0312b55";
    verify(id, sig)?;

    Ok(())
}
````

Cargo.toml:
````toml
[package]
name = "sig"
version = "0.1.0"
edition = "2021"

[dependencies]
k256 = { version = "0.11", features = [ "schnorr" ] }
serde_json = "1.0"
hex = "0.4"
secp256k1 = { version = "0.24", features = [ "std", "alloc", "rand", "rand-std" ] }
````
